pipeline {
  agent any

  tools {
    nodejs "node"
  }

  parameters {
    string(name: 'container_name', defaultValue: 'pareja6', description: 'Nombre del contenedor de docker.')
    string(name: 'image_name', defaultValue: 'fraced97/pareja6', description: 'Nombre de la imagene docker.')
    string(name: 'tag_image', defaultValue: 'lts', description: 'Tag de la imagen de la página.')
    string(name: 'container_port', defaultValue: '80', description: 'Puerto que usa el contenedor')
  }

  stages {
    

    stage('practica7') {
      steps {
          sshagent(['vmkey']){
            sh "ssh -o StrictHostKeyChecking=no -l pablorocad@34.125.9.93 'terraform -v'"  
          }
      }
    }

  }

}