- hosts: dev
  tasks:
  - name: "sync website"
    synchronize:
      src: ./Practica-3/dist/practica-3
      dest: /var/www/
      archive: no
      checksum: yes
      recursive: yes
      delete: yes
    become: no