- hosts: produccion
  tasks:
  - name: "sync website"
    synchronize:
      src: ../Practicas/Practica-3/dist/practica-3/
      dest: /var/www/
      archive: no
      checksum: yes
      recursive: yes
      delete: yes
    become: no