apiVersion: v1
kind: Service
metadata:
  name: p6-back-lb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      name: http
  selector:
    role: p6-back